spring:
  datasource:
    url: jdbc:mysql://47.107.153.16:3306/guestdb
    username: guestuser
    password: Abcde12345_
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhonghuasheng.springboot.entity