server:
  port: 8080
  servlet:
    context-path: /log
  tomcat:
    max-threads: 1000
    min-spare-threads: 10
### 方式一通过@Slf4j来手动写代码实现
logging:
  file:
    name: baselog.log
    path: /var/log/
### 方式二通过actuator的内置功能来实现 http://localhost:8080/log/actuator/loggers/cn
management:
  endpoints:
    web:
      exposure:
        include: loggers
  endpoint:
    health:
      show-details: always